spring.application.name=chat-app
spring.cloud.config.profile=
#
# Configuration server
spring.config.import=optional:configserver:http://localhost:8888
#

# DB connection settings
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=


# JPA
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=
spring.jpa.properties.hibernate.format_sql=
spring.jpa.database=
spring.jpa.database-platform=
# Custom sql files
#spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql,messages-1.sql,messages-2.sql,messages-3.sql,messages-4.sql,messages-5.sql

# API Documentation     [ https://springdoc.org/properties.html ]
springdoc.swagger-ui.path=
#springdoc.packages-to-scan=
springdoc.show-actuator=
springdoc.model-and-view-allowed=
springdoc.writer-with-default-pretty-printer=

# EUREKA
#eureka.client.serviceUrl.defaultZone=
#eureka.instance.preferIpAddress=true

#spring.banner.location=classpath:
