spring.application.name=chat-app
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# default port is 8080
#server.port=8088
#server.address=127.0.0.2
#server.address=${SERVER_HOST}

# DB connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=postgres
spring.datasource.password=qwe123


# JPA
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Custom sql files
#spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql,messages-1.sql,messages-2.sql,messages-3.sql,messages-4.sql,messages-5.sql

# API Documentation     [ https://springdoc.org/properties.html ]
springdoc.swagger-ui.path=/apis
#springdoc.packages-to-scan=*
springdoc.show-actuator=true
springdoc.model-and-view-allowed=true
springdoc.writer-with-default-pretty-printer=true

# EUREKA
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.instance.preferIpAddress=true

#spring.banner.location=classpath:/banner-gb.txt
